seed_everything: 42

trainer:
  max_epochs: 5
  logger:
  - class_path: CSVLogger
    init_args:
      save_dir: . 
      name: "logs"
  callbacks: 
    - class_path: ConfusionMatrix
    - class_path: ROC
    - class_path: SNRAccuracy
      init_args:
        snr_range:
        - 5
        - 15
        bins: 10


model:
  learning_rate: 0.0005
  token_width: 4096

data:
  data_dir: "/scratch/tmp/swein/ggwd/output/long/data"
  batch_size: 64
  num_workers: 4
