seed_everything: 42

trainer:
  max_epochs: 10
  logger:
  - class_path: CSVLogger
    init_args:
      save_dir: . 
      name: "logs"
  callbacks: 
    - class_path: Summary
    - class_path: ConfusionMatrix
    - class_path: ROC
    - class_path: SNRAccuracy
      init_args:
        snr_range:
        - 5
        - 15
        bins: 10
    - class_path: VisualizeAttention
    - class_path: AttentionHeatMap
    - class_path: SNRBinnedAttentionHeatMap


model:
  num_tokens: 16
  embed_dim: 64
  ff_dim: 512
  learning_rate: 0.001

data:
  data_dir: "/scratch/tmp/swein/ggwd/output/long/bugfix"
  batch_size: 64
  num_workers: 4
