seed_everything: 42

trainer:
  max_epochs: 3
  logger:
  - class_path: CSVLogger
    init_args:
      save_dir: . 
      name: "logs"
  callbacks: 
    - class_path: ConfusionMatrix
    - class_path: ROC
    - class_path: SNRAccuracy


model:
  learning_rate: 0.0005
  token_width: 4096

data:
  data_dir: "/scratch/tmp/swein/ggwd/output/long/data"
  batch_size: 64
  num_workers: 4
